[project]
name = "finalproject-ulyanov-m26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nikolai_Ulyanov", email = "kolyas18@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
valutatrade = "valutatrade_hub.cli.interface:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.uv.build-backend]
module-name = "valutatrade_hub"
module-root = ""

[tool.valutatrade]
data_dir = "data"
rates_ttl_seconds = 300
default_base_currency = "USD"
log_file = "logs/actions.log"
log_format = "%(asctime)s %(levelname)s %(message)s"
